apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ashupodx1
  name: ashupodx1
spec:
  imagePullSecrets: # for calling secret 
  - name: ashuocr # name of secret in current namesapce 
  containers:
  - command:
    - ping
    - fb.com
    image: phx.ocir.io/axmbtg8judkl/myalpine:v1
    name: ashupodx1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
