apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: ashutoshhpod1
spec:
  containers:
  - command:
    - sleep
    - "10000"
    image: busybox
    name: ashutoshhpod1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    delvex: ashutoshh11 
  name: ashupod2
spec:
  containers:
  - image: nginx
    name: ashupod2
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
